<?xml version="1.0" encoding="utf-8"?><Database Name="CatanDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=r0unjrd18x.database.windows.net;Initial Catalog=CatanDB;Persist Security Info=True;User ID=dba" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CatanDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PlayLobby" Member="PlayLobbies">
    <Type Name="PlayLobby">
      <Column Name="LobbyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HostPlayer" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MyTurn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sheep" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IronOre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Wood" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Wheat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Brick" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settlement" Member="Settlements">
    <Type Name="Settlement">
      <Column Name="SettlementID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Upgraded" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Lobby" Member="Lobbies">
    <Type Name="Lobby">
      <Column Name="LobbyId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LobbyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsWaitingForPlayers" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsUpdate" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiceRollllllllllllllllllllol" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>